


[window]
padding.x = 10
padding.y = 10
dynamic_title = true
opacity = 0.8
blur = true

[font]
normal.family = 'MesloLGS Nerd Font Mono'
size = 11

[env]
TERM = "alacritty"

[cursor.style]
shape = 'block'

[general]
import = ["/home/Allu/.cache/wal/colors-alacritty.toml"]
